<?php

/* This is for common scripts for the entire site */

?>

    <script src="//ajax.googleapis.com/ajax/libs/jquery/2.1.0/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/fastclick/0.6.11/fastclick.js"></script>
    <script src="<?php echo $config->urls->templates?>js/foundation/foundation.js"></script>
    <!-- Topbar.js is here since it is needed in all pages -->
    <script src="<?php echo $config->urls->templates?>js/foundation/foundation.topbar.js"></script>