<?php

/* This is for common scripts for the entire site */

?>

    <script src="<?php echo $config->urls->templates?>js/jquery-1.10.12.min.js"></script>
    <script src="<?php echo $config->urls->templates?>js/vendor/fastclick.js"></script>
    <script src="<?php echo $config->urls->templates?>js/foundation/foundation.js"></script>
    <script src="<?php echo $config->urls->templates?>js/foundation/foundation.topbar.js"></script>